### PR TITLE
Fix numerical user ids

### LINKED ISSUE #60: App crash with users with numerical IDs
App crashed with users with numerical IDs.

### PR DESCRIPTION
**Pull request by Ivansss**
Fix #60

### CODE REVIEW

**Comment by mario** [comment]
When can it be numerical

**Comment by Ivansss** [comment]
For example, just try creating a user "123456"

**Comment by mario** [comment]
Should still be a string xD

**Comment by Ivansss** [comment]
I receive it as a long not as a string.

**Pull request merged**
