### PR TITLE
i18n: Remove and correct apostrophe

### PR DESCRIPTION
**Pull request by Valdnet**
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Comment by rakekniven** [comment]
Hi @Valdnet, 

personally, I like navigation information like "Menu > Submenu > Item" to be in apostrophe or bold so that it is distinct and recognisable from the text.
We should have a definition for the complete project on how to handle this.

What do you think?

**Comment by Valdnet** [comment]
In my opinion, menu paths should not be in apostrophes.
However, application names etc. should be in apostrophes.

**Comment by rakekniven** [comment]
As written this is my opinion, nothing more :-) 

1. Go to Settings -> Defaults -> ImportantSetting and adapt it to your needs
1. Go to **Settings -> Defaults -> ImportantSetting** and adapt it to your needs
1. Go to "Settings -> Defaults -> ImportantSetting" and adapt it to your needs
1. Go to 'Settings -> Defaults -> ImportantSetting' and adapt it to your needs
1. Go to _Settings -> Defaults -> ImportantSetting_ and adapt it to your needs

Which is the one to read best?

In the documentation, I read over it if a navigation reference in continuous text is not highlighted in some way.

**Comment by Valdnet** [comment]
> Which is the one to read best?

It is most readable in items 2 and 5 😉.
Example 3 may be reconsidered.

After "Go to" I would write a colon, example:
Go to: _Settings -> Defaults -> ImportantSetting_ and adapt it to your needs

**Comment by SystemKeeper** [comment]
Hello @Valdnet & @rakekniven,

I'm generally fine with adjusting this, also I think it would make sense to have a general guidline how this should be handled.
My first thought of the changes proposed in this PR was that keeping the quotes around `"Devices & sessions"`, but removing them for the navigation reference is weird. As bold or italic might not be possible in all cases, I'd go with example 3 (or at least use it as a fallback, if 2 is not possible).

**Comment by rakekniven** [comment]
Please merge #971 first as this has grammar errors. This PR needs to be adapted later.

**Comment by Ivansss** [comment]
> Please merge https://github.com/nextcloud/talk-ios/pull/971 first as this has grammar errors. This PR needs to be adapted later.

Merged :)

**Review by Ivansss — APPROVED** [review]

**Pull request merged**
