### PR TITLE
Update icons

### PR DESCRIPTION
**Pull request by marcoambrosini**

### CODE REVIEW

**Comment by marcoambrosini** [comment]
@Ivansss what do you need here?

**Comment by Ivansss** [comment]
@marcoambrosini I would need the links to the SVGs for the other mime types, but I guess I can grab them from this comment, right?
https://github.com/nextcloud/files-clients/issues/46#issuecomment-1997473329
Also, are there any plans to add new icons for `audio`, `vcard`, and `zip` files?
https://github.com/nextcloud/files-clients/issues/46#issuecomment-2022611311

**Comment by AndyScherzinger** [comment]
yes, see server commit https://github.com/nextcloud/server/commit/1e046196759eefd3246bf95bffe3b8f8c0406069#diff-4a8aeb733f87b3e65429e618b34c71774b5286d24c1d51e0df4430a94c66893b `core/img/filetypes/*` for updated file type icons.

@Ivansss If you let me know which exact size you need them to I can update this PR

**Comment by AndyScherzinger** [comment]
https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/chat-placeholder.imageset/chat-placeholder.png
https://fonts.google.com/icons?icon.query=bubble&selected=Material+Symbols+Outlined:mode_comment:FILL@1;wght@400;GRAD@0;opsz@24&icon.size=24&icon.color=%23e8eaed

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/contact.imageset/contacts.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/text-vcard.svg or https://github.com/nextcloud/contacts/blob/main/img/app.svg
dependeing on the actual use case (user or vcard/contact)

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/contacts-placeholder.imageset/contacts-placeholder.png
https://github.com/nextcloud/contacts/blob/main/img/app.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/error.imageset/error.png
https://fonts.google.com/icons?icon.query=error&selected=Material+Symbols+Outlined:report:FILL@1;wght@400;GRAD@0;opsz@24&icon.size=24&icon.color=%23ff3b30

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/file-audio-chat-preview.imageset/file-audio-preview.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/audio.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/file-audio.imageset/file-audio.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/audio.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/file-avatar.imageset/icon-conversation-text-bright.svg
*TODO*

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/file-chat-preview.imageset/file-default-preview.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/file.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/file-document-chat-preview.imageset/file-document-chat-preview.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/x-office-document.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/file-document.imageset/file-document.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/x-office-document.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/file-image-chat-preview.imageset/file-image-chat-preview.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/image.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/file-image.imageset/file-image.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/image.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/file-pdf-chat-preview.imageset/file-pdf-chat-preview.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/application-pdf.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/file-pdf.imageset/file-pdf.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/application-pdf.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/file-presentation-chat-preview.imageset/file-presentation-chat-preview.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/x-office-presentation.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/file-presentation.imageset/file-presentation.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/x-office-presentation.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/file-spreadsheet-chat-preview.imageset/file-spreadsheet-chat-preview.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/x-office-spreadsheet.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/file-spreadsheet.imageset/file-spreadsheet.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/x-office-spreadsheet.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/file-text-chat-preview.imageset/file-text-chat-preview.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/text.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/file-text.imageset/file-text.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/text.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/file-vcard-chat-preview.imageset/file-vcard-chat-preview.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/text-vcard.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/file-vcard.imageset/file-vcard.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/text-vcard.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/file-video-chat-preview.imageset/file-video-chat-preview.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/video.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/file-video.imageset/file-video.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/video.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/file-zip-chat-preview.imageset/file-zip-chat-preview.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/package-x-generic.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/file-zip.imageset/file-zip.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/package-x-generic.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/file.imageset/file.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/file.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/folder-chat-preview.imageset/folder-default-preview.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/folder.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/folder-placeholder.imageset/folder-placeholder.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/folder.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/folder.imageset/folder.png
https://github.com/nextcloud/server/blob/master/core/img/filetypes/folder.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/group-avatar.imageset/icon-conversation-group-bright.svg
*TODO*

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/lobby-placeholder.imageset/lobby-placeholder.png
https://fonts.google.com/icons?icon.query=bell&selected=Material+Symbols+Outlined:room_service:FILL@1;wght@400;GRAD@0;opsz@24&icon.size=24&icon.color=%23d5d5d5

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/lobby.imageset/lobby.png
https://fonts.google.com/icons?icon.query=bell&selected=Material+Symbols+Outlined:room_service:FILL@1;wght@400;GRAD@0;opsz@24&icon.size=24&icon.color=%236d6d72

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/mail-avatar.imageset/icon-conversation-mail-bright.svg
*TODO*

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/navigation-home.imageset/navigation-home.png
https://github.com/nextcloud/server/blob/master/core/img/places/home.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/open-avatar.imageset/icon-open-conversation-bright.svg
*TODO*

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/password-avatar.imageset/icon-conversation-password-bright.svg
*TODO*

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/public-avatar.imageset/icon-conversation-public-bright.svg
*TODO*

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/public.imageset/public.png
https://github.com/nextcloud/server/blob/master/core/img/places/link.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/qrcode-scan.imageset/qrcode-scan.png
https://fonts.google.com/icons?icon.query=qr&selected=Material+Symbols+Outlined:qr_code_scanner:FILL@1;wght@400;GRAD@0;opsz@24&icon.size=24&icon.color=%236d6d72

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/sharing.imageset/sharing.png
https://github.com/nextcloud/server/blob/master/core/img/actions/share.svg (to be used for internal shares)
https://github.com/nextcloud/server/blob/master/apps/settings/img/share.svg (generic one, as of now)

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/twitter.imageset/twitter.png
https://github.com/nextcloud/server/blob/master/core/img/actions/twitter.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/user-avatar.imageset/icon-conversation-user-bright.svg
*TODO*

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/user-status-away-10.imageset/user-status-away-10.png
https://github.com/nextcloud/android/blob/master/drawable_resources/user-status-away.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/user-status-away.imageset/user-status-away.png
https://github.com/nextcloud/android/blob/master/drawable_resources/user-status-away.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/user-status-dnd-10.imageset/user-status-dnd-10.png
https://github.com/nextcloud/android/blob/master/drawable_resources/user-status-dnd.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/user-status-dnd.imageset/user-status-dnd.png
https://github.com/nextcloud/android/blob/master/drawable_resources/user-status-dnd.svg

---

https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/Images.xcassets/user-status-online-10.imageset/user-status-online-10.png
*TODO*

**Comment by SystemKeeper** [comment]
* First batch at https://github.com/nextcloud/talk-ios/pull/1730
* Todo at https://github.com/nextcloud/talk-ios/issues/1731

**Pull request closed without merging**
