### PR TITLE
Implement typing indicators

### LINKED ISSUE #1181: Support "Typing indicators"
- Overview issue at https://github.com/nextcloud/spreed/issues/9248

---

- [ ] When the chat input is non empty a signaling message is sent in periodical interval
- [ ] When the signaling messages is received a small max contrast line is shown above the chat input

### PR DESCRIPTION
**Pull request by SystemKeeper**
Fixes #1181 
Needs https://github.com/Ivansss/SlackTextViewController/pull/21

Some assumption about the open questions at https://github.com/nextcloud/spreed/issues/9272#issuecomment-1528757620 are made in this PR, but those should be adjustable pretty easily.
Works for iOS <-> iOS for now.

### CODE REVIEW

**Review by Ivansss — APPROVED** [review]

**Comment by AndyXheli** [comment]
Hey @SystemKeeper quick question should the typing indicator work ? So I have two mobile devices running 17.0.0 (3) and server is running no 27.0.0 RC3 and I'm not seeing anything ? Do I need high performance backend for this ?

**Comment by SystemKeeper** [comment]
Yes, HPB is currently required for typing indicators. The next version will add a hint about the need for HPB.

**Comment by AndyXheli** [comment]
Thank you!! For the quick response!! I'm guessing there won't be any implementation without HPB ?

**Comment by SystemKeeper** [comment]
At least for iOS there is currently no plan to implement it for internal signaling, that would require some major changes on how we handle internal signaling. 
I am not sure how the current state for web is, could be that web-web would work without hpb, but don’t know.

**Pull request merged**
