### PR TITLE
Add push-to-talk functionality

### PR DESCRIPTION
**Pull request by SystemKeeper**
Currently talk-ios uses a dialog to display a warning when participant is force-muted by a moderator. In contrast nextcloud talk web uses a toast to display the warning, which will disappear after 7s (default timeout for toasts in nextcloud).

This PR changes the behaviour in talk-ios to also use a toast which will disappear automatically but can be dismissed by the user as well.

Before

image

After

image

### CODE REVIEW

**Comment by jancborchardt** [comment]
> use a toast which will disappear automatically but can be dismissed by the user as well.

@SystemKeeper I am not so familiar with iOS (sometimes using a device but don’t have my own), is this toast a common pattern in iOS? As far as I remember I haven’t seen anything of the sort so far, or do you have a reference? :)

Maybe it would make more sense to use a nonmodal popover for this: https://developer.apple.com/design/human-interface-guidelines/ios/views/popovers/
It could show the text, be dismissed when tapping anywhere except the popover, and it could point to your own mute button, indicating the status.

And I assume this would appear in 2 cases:
- When you join the call initially
- When you tap on your own microphone icon

**Comment by Ivansss** [comment]
@jancborchardt I think the toast is fine. The one we are using is not really iOS native, but iOS 14 is now showing some toasts for example when you paste something from the clipbloard.

We are using the toast that @SystemKeeper used here for notifying about things like "message copied", "mic muted", "camera disabled"...

The only thing I'm not really sure here is if the toast is good for warning about that a moderator muted you. Maybe you could miss the toast if you are not looking at the screen. Instead you can't miss it if we show a dialog.

What do you think @SystemKeeper @jancborchardt ?

**Comment by jancborchardt** [comment]
> The only thing I'm not really sure here is if the toast is good for warning about that a moderator muted you. Maybe you could miss the toast if you are not looking at the screen. Instead you can't miss it if we show a dialog.

That’s why I was proposing the popover. :) It behaves like a dialog in that you need to tap somewhere to dismiss it, but also we can have it point to the mute button, which makes people aware of the context, and gives feedback as to why pressing the audio on/off button does not work.

E.g. if you are muted by a moderator and you try to unmute, this popover would also show, originating from the button you just tapped. :)

**Comment by SystemKeeper** [comment]
@jancborchardt Those toasts are already used in the ios-talk app:

image

Just not for being force-muted. That’s why I adapted it this way. WhatsApp is using something similar:

image

@Ivansss Personally I think a toast would be enough: In my case participants are often muted, because everyone should be muted. In that case a notification which does not require user interaction would be enough and it‘s same in Web, the message disappears automatically.

I guess in a follow up commit we could do this more inline with iOS 14 and display the toast on top of the screen and maybe show a little „muted icon“ in a corner? This way it’s always clear to the user that he’s muted, regardless if he did see the toast or not.

**Comment by Ivansss** [comment]
@jancborchardt That popovers are usually used in iPad interfaces. They even say "Avoid displaying popovers on iPhones." below the image in the link you shared https://developer.apple.com/design/human-interface-guidelines/ios/views/popovers/

**Comment by SystemKeeper** [comment]
> E.g. if you are muted by a moderator and you try to unmute, this popover would also show, originating from the button you just tapped. :)

Hm, just to make sure I fully get this: When you’re force muted and you unmute yourself you want to display „Microphone enabled“ in the same popup, Right ?

**Comment by SystemKeeper** [comment]
@jancborchardt For reference, this is what iOS 14 does when changing the ringer state:
image

Quick implementation of a permanent mute-indicator:

image
image
image

> [...] and gives feedback as to why pressing the audio on/off button does not work.

Maybe I'm missing something, but getting muted by a moderator does not mean I can't unmute myself, does it? So there would be no other toast/popover/... needed, because the button always works?!

Let me know what you think :-)

**Comment by SystemKeeper** [comment]
Thinking about it, we could also display the (un-)mute button, in case we’re muted. This way it’s always clear to the user and one can immediately unmute himself. Not sure if this is good UX however 🧐

**Comment by Ivansss** [comment]
> Maybe I'm missing something, but getting muted by a moderator does not mean I can't unmute myself, does it? So there would be no other toast/popover/... needed, because the button always works?!

You are right. Even if you have been muted by a moderator, you can unmute yourself.

I like the idea of the mute indicator, but this will only work in video calls and not in voice calls :/

My only concern here is if we should really make users aware that a moderator has muted them (so we show a permanent dialog as before) or if it is good enough to just show a toast for 7secs (even if users can miss it if they are not looking at the screen).

**Comment by SystemKeeper** [comment]
> I like the idea of the mute indicator, but this will only work in video calls and not in voice calls :/

In voice calls the UI Elements are always visible, so there’s already an indicator via the mute button.

Thinking about the idea with permanently showing the mute button: this would also be a requirement for a future push-to-talk implementation, wouldn’t it? Short touch: unmute, press and hold: push-to-talk?

Regarding the toast, I still would argue it should be consistent in web and mobile, therefore a 7s toast would make sense. But I‘m fine either way :)

**Comment by SystemKeeper** [comment]
> Thinking about the idea with permanently showing the mute button: this would also be a requirement for a future push-to-talk implementation, wouldn’t it? Short touch: unmute, press and hold: push-to-talk?

Quick implementation:

Force-muted:
image

While muted:
image

When controls show:
image

Button shows when force muted and stays there (also when you mute yourself of course). Long press could then be used for push-to-talk I guess?

**Comment by SystemKeeper** [comment]
Latest commit permanently shows the unmute-button if you're muted. It also adds push-to-talk: Press-and-hold the unmute button to temporarily unmute yourself. You're muted again if you release the button.

**Review by Ivansss — APPROVED** [review]
Tested and works!

**Comment by Ivansss** [comment]
Awesome work @SystemKeeper :)

**Pull request merged**
