### PR TITLE
Add "Go to file" to file-conversations

### PR DESCRIPTION
**Pull request by SystemKeeper**
Currently there's no way to open the file which belongs to a file-conversation. This PR adds a "Go to file" action to the room info which opens the file in nextcloud app.

**ToDo**
-  Figure out how we can get the file path with just the fileID.  To open a file in the iOS Nextcloud App, we need the internal link (done) and the path of the file. I've yet to figure out how to retrieve the path. Files which are shared in a room automatically have a path attribute, doesn't look like there's something like this for a file-room
- Check if it's ok to show the image of the filetype or if we need a dedicated icon here

image

image

### CODE REVIEW

**Comment by SystemKeeper** [comment]
> * Check if it's ok to show the image of the filetype or if we need a dedicated icon here

@jancborchardt  Do you have any recommendation on this one? :-)

**Comment by SystemKeeper** [comment]
> * Figure out how we can get the file path with just the fileID.  To open a file in the iOS Nextcloud App, we need the internal link (done) and the path of the file. I've yet to figure out how to retrieve the path. Files which are shared in a room automatically have a path attribute, doesn't look like there's something like this for a file-room

Resolved, thanks to @Ivansss !

**Review by Ivansss — APPROVED** [review]
Tested and works 👍

**Comment by Ivansss** [comment]
Awesome work once again ;)

**Pull request merged**
