### PR TITLE
Update webrtc 116.5845.0

### PR DESCRIPTION
**Pull request by Ivansss**

### CODE REVIEW

**Review by SystemKeeper — APPROVED** [review]
Tested and works 👍 

Maybe we should think about adding the lib also via SPM: https://developer.apple.com/documentation/xcode/distributing-binary-frameworks-as-swift-packages

**Comment by SystemKeeper** [comment]
Judging from https://webrtc.googlesource.com/src.git/+/44bc8e96ed88005fec89a1cc479e291fea30d1b3/sdk/objc/components/renderer/metal/RTCMTLI420Renderer.mm#122 the fix for the 1x1 crashes we were seeing and patching ourselves should now be part of the 116 version. Can you confirm that from the sources you used to build the lib? We could then go ahead and remove our patch from the lib repo...

**Comment by Ivansss** [comment]
Yes, the fix is on the source files we used to build the lib.
Should we remove (and  don't apply) the patch for the following version?
https://github.com/nextcloud-releases/talk-clients-webrtc/blob/main/ios/patches/RTCMTLVideoView.patch

Or do you think we should build a new version (e.g. 116.5845.1) without the patch?

**Comment by SystemKeeper** [comment]
> Or do you think we should build a new version (e.g. 116.5845.1) without the patch?

I would suggest dropping our patch in the next version upgrade. Our patch fixes the same issue, just in a different way/position. So for 116 it shouldn't matter one way or another.

**Pull request merged**
