### PR TITLE
Use MacOS 15, as 12 is now deprecated on GHA

### PR DESCRIPTION
**Pull request by SystemKeeper**
* Context: https://github.com/actions/runner-images/issues/10721

### CODE REVIEW

**Comment by SystemKeeper** [comment]
Cool... So MacOS 14 is green, but needs to retry some tests. MacOS 13 fails. I'd suggest we stay as long on MacOS 12 as we can and then probably move to 14. Removal is planned for october this year...

**Comment by erik-bershel** [comment]
It worth trying `macos-15`. Simulators seems to be 10-50% faster there.

**Comment by SystemKeeper** [comment]
Thank you for the tip! Let's see :)

**Review by Ivansss — APPROVED** [review]

**Pull request merged**
