### PR TITLE
show error message when voice message upload fails

### LINKED ISSUE #741: Errormessage missing when voicemessage upload fails
iPhone SE (MLM72DN/A)
iOS 15.3.1
Talk 13.1.1
NC 23.0.2
Microfon and Camera is allowed
Wi-Fi + Internet connected
All other iPhones work as expected

### Expected behavior:

When pushing the microphone button in the chat the recording of the voice message should start and when releasing the message should send.

### Actual behavior:
When pushing the microphone button to recording is automatically cancelled after 10 seconds and no messages is sent.

### PR DESCRIPTION
**Pull request by DanielStandfest**
Added logic to display an error message when the upload of a voice message fails due to missing user storage quota. 

Fixes #741

@crustulumtheoneandonly
@SystemKeeper

### CODE REVIEW

**Comment by SystemKeeper** [comment]
Hello and welcome 👋 
Thank you very much for your PR! This looks fine - the only thing is that the code you changed (and the part before) uses tabs, instead of spaces. Since the file is otherwise using completely using spaces, would you be able to change that? 😃

**Comment by DanielStandfest** [comment]
Hi, thank you.
I didn't recognize it at first.
It should be fixed now.

**Review by Ivansss — APPROVED** [review]
Thank you so much for your PR @DanielStandfest :)

**Review by SystemKeeper — APPROVED** [review]
Thank you :)

**Pull request merged**
