### PR TITLE
Adjust placeholder view constraints to safe area

### PR DESCRIPTION
**Pull request by Ivansss**

### CODE REVIEW

**Comment by SystemKeeper** [comment]
image

🤔

**Comment by Ivansss** [comment]
I couldn't find an easy fix for this problem, not as trivial as I thought.
This PR fixes the positioning of the activity indicator.
This issue of the screenshot above is tracked here https://github.com/nextcloud/talk-ios/issues/1290 and we can try to fix it in a follow-up PR.

**Comment by SystemKeeper** [comment]
> This issue of the screenshot above is tracked here #1290 and we can try to fix it in a follow-up PR.

Sorry, I though that should be the fix for exactly that…

**Review by SystemKeeper — APPROVED** [review]
Now that I know what I should test, this works as expected ;)

**Pull request merged**
