### PR TITLE
i18n: Spelling unification

### PR DESCRIPTION
**Pull request by Valdnet**
Spelling unification in Transifex.

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Review by rakekniven — APPROVED** [review]
@Ivansss  Why does GitHub think that "Localizable.strings" is binary?

**Comment by Valdnet** [comment]
@rakekniven It is explained [here](https://github.com/nextcloud/talk-ios/pull/619#issuecomment-921058662) 😉.

**Comment by Ivansss** [comment]
Did this string change in the server repo as well? @Valdnet @rakekniven

**Comment by Valdnet** [comment]
@Ivansss To avoid recoding again, it was upload as a file.

**Comment by Valdnet** [comment]
@Ivansss How can I remove a conflict? When solving it, it does not indicate anything.

**Review by rakekniven — CHANGES_REQUESTED** [review]
Something went wrong when solving conflict of Localizable.strings using the web UI.
Please do not merge.
File in branch is empty now.

**Review by rakekniven — APPROVED** [review]

**Comment by nickvergessen** [comment]
> Did this string change in the server repo as well?

yes

**Comment by Ivansss** [comment]
Thanks for the PR @Valdnet and @rakekniven :)

**Comment by SystemKeeper** [comment]
Maybe the best option would be to just edit the source file, instead of the `localizable.strings`, because the file is generated periodically by @Ivansss : https://github.com/nextcloud/talk-ios/blob/master/docs/Localization/Generate-localization-file.md ? Would make PRs and merging easier.

**Comment by Ivansss** [comment]
I think what @SystemKeeper suggested would be the best idea for future PRs @Valdnet and @rakekniven 
You can just edit source files and after merging the PR I will use the [genstrings tool ](https://github.com/nextcloud/talk-ios/blob/master/docs/Localization/Generate-localization-file.md) to update `localizable.strings`

**Comment by Valdnet** [comment]
@Ivansss Thanks a lot 👍. This will make it easier for us to edit the file with the text strings.

**Comment by rakekniven** [comment]
You handle it different then Nextcloud ios app, or?

There I often only change https://github.com/nextcloud/ios/blob/develop/iOSClient/Supporting%20Files/en.lproj/Localizable.strings to make source string adaptions.

**Comment by Ivansss** [comment]
Thanks for pointing to that file @rakekniven :)

I just noticed that https://github.com/nextcloud/ios/blob/develop/iOSClient/Supporting%20Files/en.lproj/Localizable.strings is UTF-8 encoded, and that's the file that is sent to transifex. So it seems that transifex also accepts UTF-8.
We were just not sure while discussing it [here](https://github.com/nextcloud/talk-ios/pull/619#issuecomment-921058662).

So we could convert https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/en.lproj/Localizable.strings to UTF-8 and that way it could be easily modified (and also we would be able to see the changes in the diff).

**Comment by Ivansss** [comment]
[en.lproj/Localizable.strings](https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/en.lproj/Localizable.strings) is now UTF-8 encoded.
Now the changes in that file are shown nicely in the diff https://github.com/nextcloud/talk-ios/commit/5b7a6456785e4d66c55526f57f084c71542e4613 :)
Also the sync with transifex works as expected!

**Pull request merged**
